CC = gcc
CFLAGS = -Wall -Wextra -g

all: vector-seq-processes

vector-seq-processes: vector-seq-processes.c
	$(CC) $(CFLAGS) -o vector-seq-processes vector-seq-processes.c

clean:
	rm -f vector-seq-processes